export enum ArtistToolResponse {
  MISSING_ARTIST_NAME = "MISSING_ARTIST_NAME",
  CREATED_ARTIST = "CREATED_ARTIST",
  NO_ARTISTS = "NO_ARTISTS",
  NO_CAMPAIGNS = "NO_CAMPAIGNS",
  ARTIST_LIST = "ARTIST_LIST",
  CAMPAIGN_LIST = "CAMPAIGN_LIST",
  MISSING_ARTIST_CLIENT_ID = "MISSING_ARTIST_CLIENT_ID",
  CREATED_CAMPAIGN = "CREATED_CAMPAIGN",
}
