export enum ArtistToolResponse {
  MISSING_ARTIST_NAME = "MISSING_ARTIST_NAME",
  CREATED_ARTIST = "CREATED_ARTIST",
  NO_ARTISTS = "NO_ARTISTS",
  NO_CAMPAIGNS = "NO_CAMPAIGNS",
  ARTIST_LIST = "ARTIST_LIST",
  MISSING_ARTIST_TIKTOK_USERNAME = "MISSING_ARTIST_TIKTOK_USERNAME",
  TIKTOK_TRENDS = "TIKTOK_TRENDS",
  CAMPAIGN_LIST = "CAMPAIGN_LIST",
  MISSING_ARTIST_CLIENT_ID = "MISSING_ARTIST_CLIENT_ID",
  CREATED_CAMPAIGN = "CREATED_CAMPAIGN",
  UPDATED_ARTIST_INFO = "UPDATE_ARTIST_INFO",
  MISSING_VIDEO_URL = "MISSING_VIDEO_URL",
  VIDEO_COMMENTS = "VIDEO_COMMENTS",
  MISSING_SEGMENT_NAME_ANALYSIS_ID = "MISSING_SEGMENT_NAME_ANALYSIS_ID",
  MISSING_PITCH_NAME = "MISSING_PITCH_NAME",
  FUNNEL_SEGMENT_REPORT = "FUNNEL_SEGMENT_REPORT",
  FUNNEL_PITCH_REPORT = "FUNNEL_PITCH_REPORT",
  INSTRUMENTAL_STYLE_SUGGESTION = "INSTRUMENTAL_STYLE_SUGGESTION",
}

export enum Tools {
  getScoreInfo = "getScoreInfo",
  getVideosInfo = "getVideosInfo",
  getSegmentsReport = "getSegmentsReport",
  getPitchReport = "getPitchReport",
  getArtistAnalysis = "getArtistAnalysis",
  getInstrumentalStyleSuggestions = "getInstrumentalStyleSuggestions",
}
