export enum ArtistToolResponse {
  MISSING_ARTIST_NAME = "MISSING_ARTIST_NAME",
  CREATED_ARTIST = "CREATED_ARTIST",
  NO_ARTISTS = "NO_ARTISTS",
  NO_CAMPAIGNS = "NO_CAMPAIGNS",
  ARTIST_LIST = "ARTIST_LIST",
  MISSING_ARTIST_TIKTOK_USERNAME = "MISSING_ARTIST_TIKTOK_USERNAME",
  TIKTOK_TRENDS = "TIKTOK_TRENDS",
  CAMPAIGN_LIST = "CAMPAIGN_LIST",
  MISSING_ARTIST_CLIENT_ID = "MISSING_ARTIST_CLIENT_ID",
  CREATED_CAMPAIGN = "CREATED_CAMPAIGN",
  UPDATED_ARTIST_INFO = "UPDATE_ARTIST_INFO",
}
