create table "public"."account_artist_ids" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "account_id" uuid default gen_random_uuid(),
    "artist_id" uuid default gen_random_uuid()
);


alter table "public"."account_artist_ids" enable row level security;

alter table "public"."artist_social_links" enable row level security;

CREATE UNIQUE INDEX account_artist_ids_pkey ON public.account_artist_ids USING btree (id);

alter table "public"."account_artist_ids" add constraint "account_artist_ids_pkey" PRIMARY KEY using index "account_artist_ids_pkey";

alter table "public"."account_artist_ids" add constraint "account_artist_ids_account_id_fkey" FOREIGN KEY (account_id) REFERENCES accounts(id) not valid;

alter table "public"."account_artist_ids" validate constraint "account_artist_ids_account_id_fkey";

alter table "public"."account_artist_ids" add constraint "account_artist_ids_artist_id_fkey" FOREIGN KEY (artist_id) REFERENCES artists(id) not valid;

alter table "public"."account_artist_ids" validate constraint "account_artist_ids_artist_id_fkey";

grant delete on table "public"."account_artist_ids" to "anon";

grant insert on table "public"."account_artist_ids" to "anon";

grant references on table "public"."account_artist_ids" to "anon";

grant select on table "public"."account_artist_ids" to "anon";

grant trigger on table "public"."account_artist_ids" to "anon";

grant truncate on table "public"."account_artist_ids" to "anon";

grant update on table "public"."account_artist_ids" to "anon";

grant delete on table "public"."account_artist_ids" to "authenticated";

grant insert on table "public"."account_artist_ids" to "authenticated";

grant references on table "public"."account_artist_ids" to "authenticated";

grant select on table "public"."account_artist_ids" to "authenticated";

grant trigger on table "public"."account_artist_ids" to "authenticated";

grant truncate on table "public"."account_artist_ids" to "authenticated";

grant update on table "public"."account_artist_ids" to "authenticated";

grant delete on table "public"."account_artist_ids" to "service_role";

grant insert on table "public"."account_artist_ids" to "service_role";

grant references on table "public"."account_artist_ids" to "service_role";

grant select on table "public"."account_artist_ids" to "service_role";

grant trigger on table "public"."account_artist_ids" to "service_role";

grant truncate on table "public"."account_artist_ids" to "service_role";

grant update on table "public"."account_artist_ids" to "service_role";


